CREATE TABLE IM(
    MEMBER_NUM    NUMBER(5, 0)   
,   IDX NUMBER(5,0)			
,   CODE VARCHAR2(30)	
,   NAME VARCHAR2(30)		
,   PRICE NUMBER(5,0)
,   MARKET VARCHAR2(40)
,   REMARKS VARCHAR2(360)
,   QUANTITY NUMBER(5,0)
,   REGDATE VARCHAR2(300)
);
drop table IM;
SELECT * FROM im;
CREATE TABLE MEMBERS(
	  MEMBER_NUM    NUMBER(5, 0)   PRIMARY KEY
    , MEMBER_NAME   VARCHAR2(30)   NOT NULL
    , MEMBER_EMAIL  VARCHAR2(360) 
    , MEMBER_PWD    VARCHAR2(60)   NOT NULL
);
